[package]
name = "httpbin-rs"
version = "0.1.0"
edition = "2021"
authors = ["duskmoon (Campbell He) <kp.campbell.he@duskmoon314.com>"]
description = "HTTP Request & Response Service pretty like [httpbin](http://httpbin.org) but powered by Rust & Poem"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[dependencies]
base64 = "0.13.1"
chrono = "0.4.22"
chrono-tz = "0.8.0"
clap = { version = "4.0.22", features = ["derive"] }
cron = "0.12.0"
digest = "0.10.5"
infer = "0.13.0"
md-5 = "0.10.5"
poem = "1.3.48"
poem-openapi = { version = "2.0.19", features = [
    "swagger-ui",
    "rapidoc",
    "redoc",
    "uuid",
] }
rand = "0.8.5"
serde = "1.0.147"
serde_json = "1.0.87"
serde_urlencoded = "0.7.1"
sha2 = "0.10.6"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = { version = "1.2.1", features = ["v3", "v4", "v5"] }

[dev-dependencies]
rusty-hook = "0.11.2"
