[package]
name = "httpbin-rs"
version = "0.1.0"
edition = "2021"
authors = ["duskmoon (Campbell He) <kp.campbell.he@duskmoon314.com>"]
description = "HTTP Request & Response Service pretty like [httpbin](http://httpbin.org) but powered by Rust & Poem"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
chrono = "0.4.22"
chrono-tz = "0.6.3"
clap = { version = "3.2.17", features = ["derive"] }
cron = "0.11.0"
digest = "0.10.3"
md-5 = "0.10.1"
poem = "1.3.40"
poem-openapi = { version = "2.0.10", features = [
    "swagger-ui",
    "rapidoc",
    "redoc",
    "uuid",
] }
rand = "0.8.5"
serde = "1.0.143"
serde_json = "1.0.83"
serde_urlencoded = "0.7.1"
sha2 = "0.10.2"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
uuid = { version = "1.1.2", features = ["v3", "v4", "v5"] }

[dev-dependencies]
rusty-hook = "0.11.2"
