name: Changelog Check

on:
  pull_request:
    branches:
      - main

jobs:
  changelog:
    name: Changelog Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
