name: Rust check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: check fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check
      - name: check clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: check build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: check test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
